services:
  fastapi_backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sports_api_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - backend-network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload


  aider:
    image: paulgauthier/aider-full:latest
    container_name: sports_aider
    env_file:
      - .env
    environment:
      - OLLAMA_API_BASE=https://oll.chadzone.top
      - OLLAMA_MODEL=ollama_chat/llama3.2
      - DEEPSEEK_API_BASE=https://oll.chadzone.top
      - DEEPSEEK_MODEL=ollama_chat/deepseek-r1:14b
    volumes:
      - .:/app
    tty: true
    stdin_open: true
    working_dir: /app
    networks:
      - backend-network


networks:
  backend-network:
    driver: bridge

