version: '3'

services:
  fastapi_backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sports_api_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./:/app
    networks:
      - sports-api-backend-network

  vue_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue_frontend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app/frontend
    networks:
      - sports-api-backend-network

networks:
  sports-api-backend-network:
    name: sports-api-backend-network
    driver: bridge
