services:
  fastapi_backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sports_api_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - sports-api-backend-network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --log-level info --proxy-headers


  # aider:
  #   image: paulgauthier/aider:latest
  #   container_name: sports_aider
  #   env_file:
  #     - .env
  #   environment:
  #     - OLLAMA_API_BASE=https://oll.chadzone.top
  #     - OLLAMA_API_KEY=sk-8794f21da51f4658bb91577ba18e5151
  #     - OLLAMA_MODEL=ollama_chat/llama3.2
  #     - DEEPSEEK_API_BASE=https://oll.chadzone.top
  #     - DEEPSEEK_API_KEY=sk-8794f21da51f4658bb91577ba18e5151
  #     - DEEPSEEK_MODEL=ollama_chat/deepseek-r1:14b
  #   volumes:
  #     - .:/app
  #   tty: true
  #   stdin_open: true
  #   working_dir: /app
  #   networks:
  #     - backend-network


networks:
  sports-api-backend-network:
    name: sports-api-backend-network
    driver: bridge
